import { ProjectCard, DashboardKpi } from "@/types";

export const MOCK_PROJECTS: ProjectCard[] = [
  {
    id: "prj-001",
    name: "Gedung Perkantoran Tower A",
    code: "PRJ-001",
    clientName: "PT. Maju Bersama Tbk",
    location: "Jakarta Selatan",
    contractValue: 18_500_000_000,
    startDate: "2025-01-15",
    endDate: "2025-12-31",
    status: "active",
    plannedProgress: 62,
    actualProgress: 58,
    deviation: -4,
    deviationStatus: "behind",
    daysRemaining: 221,
    periodType: "weekly",
  },
  {
    id: "prj-002",
    name: "Jembatan Sungai Brantas",
    code: "PRJ-002",
    clientName: "Dinas PU Kabupaten Kediri",
    location: "Kediri, Jawa Timur",
    contractValue: 7_200_000_000,
    startDate: "2025-03-01",
    endDate: "2025-09-30",
    status: "active",
    plannedProgress: 45,
    actualProgress: 51,
    deviation: 6,
    deviationStatus: "ahead",
    daysRemaining: 130,
    periodType: "weekly",
  },
  {
    id: "prj-003",
    name: "Perumahan Griya Asri Blok C",
    code: "PRJ-003",
    clientName: "PT. Properti Nusantara",
    location: "Sidoarjo, Jawa Timur",
    contractValue: 4_800_000_000,
    startDate: "2025-02-10",
    endDate: "2025-11-30",
    status: "active",
    plannedProgress: 55,
    actualProgress: 55,
    deviation: 0,
    deviationStatus: "on_track",
    daysRemaining: 190,
    periodType: "monthly",
  },
  {
    id: "prj-004",
    name: "Renovasi Gedung Sekolah SDN 01",
    code: "PRJ-004",
    clientName: "Dinas Pendidikan Tulungagung",
    location: "Tulungagung, Jawa Timur",
    contractValue: 980_000_000,
    startDate: "2025-04-01",
    endDate: "2025-07-31",
    status: "on_hold",
    plannedProgress: 30,
    actualProgress: 22,
    deviation: -8,
    deviationStatus: "behind",
    daysRemaining: 68,
    periodType: "weekly",
  },
  {
    id: "prj-005",
    name: "Saluran Irigasi Pertanian",
    code: "PRJ-005",
    clientName: "Dinas Pertanian Blitar",
    location: "Blitar, Jawa Timur",
    contractValue: 2_300_000_000,
    startDate: "2024-10-01",
    endDate: "2025-03-31",
    status: "completed",
    plannedProgress: 100,
    actualProgress: 100,
    deviation: 0,
    deviationStatus: "on_track",
    daysRemaining: 0,
    periodType: "monthly",
  },
  {
    id: "prj-006",
    name: "Gudang Logistik Surabaya",
    code: "PRJ-006",
    clientName: "CV. Logistik Andalan",
    location: "Surabaya, Jawa Timur",
    contractValue: 3_450_000_000,
    startDate: "2025-05-01",
    endDate: "2025-12-15",
    status: "planning",
    plannedProgress: 0,
    actualProgress: 0,
    deviation: 0,
    deviationStatus: "on_track",
    daysRemaining: 205,
    periodType: "weekly",
  },
];

export const MOCK_KPI: DashboardKpi = {
  totalProjects: 6,
  activeProjects: 3,
  totalContractValue: 37_230_000_000,
  portfolioProgress: 48,
  behindSchedule: 2,
  onTrack: 3,
  ahead: 1,
};
